### ISSUE TITLE
Custom asset_path helper is not implemented

### ISSUE THREAD

**Issue by johnrees** [bokmann/font-awesome-rails#48]
I can't seem to be able to compile my assets on Rails 4.0. I've tried putting the `environment.context_class.class_eval do` method in various files (config.ru, application.rb etc) but haven't had any joy. Can anyone help? Thanks

```
$ RAILS_ENV=production bundle exec rake assets:precompile --trace
...
Custom asset_path helper is not implemented
Extend your environment context with a custom method.

    environment.context_class.class_eval do
      def asset_path(path, options = {})
      end
    end

  (in /usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/font-awesome-rails-a88a9a88f0df/app/assets/stylesheets/font-awesome.css.erb)/usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/sprockets-2.10.0/lib/sprockets/context.rb:241:in `asset_path'
/usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/sprockets-2.10.0/lib/sprockets/context.rb:261:in `font_path'
/usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/font-awesome-rails-a88a9a88f0df/app/assets/stylesheets/font-awesome.css.erb:31:in `block in singleton class'
/usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/font-awesome-rails-a88a9a88f0df/app/assets/stylesheets/font-awesome.css.erb:-5:in `instance_eval'
/usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/font-awesome-rails-a88a9a88f0df/app/assets/stylesheets/font-awesome.css.erb:-5:in `singleton class'
/usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/font-awesome-rails-a88a9a88f0df/app/assets/stylesheets/font-awesome.css.erb:-7:in `__tilt_70284069963480'
/usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
/usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
/usr/local/var/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'


```

**Comment by cmalpeli** [comment]
I just ran into this and used the solution @delner provided.....no idea why it was needed though :/

**Comment by pferdefleisch** [comment]
This was happening to me because I had `include ActionView::Helpers::AssetUrlHelper` in an initializer.
Yep.
